- name: create easyeffects config directory
  file:
    state: directory
    path: "{{ user_home_dir }}/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"

# Grabbed Laptop.json from JackHack96
# https://github.com/JackHack96/EasyEffects-Presets
- name: push easyeffects presets
  copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
  loop:
    - Laptop.json
    - No Effects.json
