- name: Fedora KDE Plasma playbook
  hosts: localhost
  tasks:
    - name: Import RPM Fusion GPG keys
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.rpm_key:
        state: present
        key: "{{ item }}"
      loop:
        - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
        - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

    - name: Enable RPM Fusion repositories
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: Enable copr repositories
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: "{{ item }}"
      loop:
        - che/nerd-fonts
      # - atim/starship

    - name: Enable Flathub repository
      when: ansible_distribution == 'Fedora'
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install system packages
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name:
          - heif-pixbuf-loader
          - libheif-tools
          - neovim
          - kate
          - google-noto-sans-runic-fonts
          - fira-code-fonts
          - fastfetch
          - steam
          - fish
          - akmod-nvidia
          - git-core
          - yt-dlp
          - aria2
          - nerd-fonts
          - torbrowser-launcher
          - btop
          - nvtop
          - gh

# ==================== RPM Fusion ==================== #
    - name: Update @core
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name: "@core"

    - name: FFmpeg
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.command: "dnf swap ffmpeg-free ffmpeg --allowerasing -y"

    - name: Codecs
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.command: 'dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y'

    - name: Update @sound-and-video
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name: "@sound-and-video"

    - name: Install hardware accelerated codecs
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name:
          - intel-media-driver
          - libva-intel-driver
          - libva-nvidia-driver

    - name: Install DVD repository
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name:
          - rpmfusion-free-release-tainted

    - name: DVD
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name:
          - libdvdcss

    - name: Firmware repo
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: present
        name:
          - rpmfusion-nonfree-release-tainted

    - name: Install firmwares
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.command: 'dnf --repo=rpmfusion-nonfree-tainted install "*-firmware" -y'
# ==================== RPM Fusion ==================== #

    - name: Remove not needed packages
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        state: absent
        name:
          - mediawriter
          - kontact
          - kmail
          - okular
          - dragonplayer
          - elisa-player
          - firewall-config
          - kamoso
          - kmahjongg
          - kmines
          - kmousetool
          - kmouth
          - kolourpaint
          - kpat
          - krdc
          - krfb
          - ktnef
          - kwrite
          - akregator
          - neochat
          - skanpage
          - korganizer
          - kaddressbook
          - kfind
          - kcharselect
          - kgpg
          - virtualbox-guest-additions
          - kwalletmanager5

    - name: Autoremove unused dependencies
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        autoremove: true

    - name: Install Homebrew packages
      when: ansible_distribution == 'Fedora'
      community.general.homebrew:
        name:
          - gallery-dl
          - topgrade

    - name: Install flatpaks from flathub
      when: ansible_distribution == 'Fedora'
      community.general.flatpak:
        name:
          - chat.simplex.simplex # SimpleX Chat
          - com.github.Anuken.Mindustry # Mindustry
          - com.github.wwmm.easyeffects # Easy Effects
          - com.heroicgameslauncher.hgl # Heroic Games Launcher
          - com.obsproject.Studio # OBS Studio
          - dev.vencord.Vesktop # Vesktop
          - io.mpv.Mpv # mpv
          - md.obsidian.Obsidian # Obsidian
          - net.davidotek.pupgui2 # ProtonUp-Qt
          - net.lutris.Lutris # Lutris
          - org.gimp.GIMP # GIMP
          - org.inkscape.Inkscape # Inkscape
          - org.kartkrew.RingRacers # Ring Racers
          - org.kde.kdenlive # Kdenlive
          - org.keepassxc.KeePassXC # KeePassXC
          - org.localsend.localsend_app # LocalSend
          - org.mozilla.Thunderbird # Thunderbird
          - org.prismlauncher.PrismLauncher # Prism Launcher
          - org.qbittorrent.qBittorrent # qBittorrent
          - org.signal.Signal # Signal Desktop
          - sh.ppy.osu # osu!
          - org.fooyin.fooyin # fooyin
          - app/org.wesnoth.Wesnoth/x86_64/stable # Battle for Wesnoth
          - com.shatteredpixel.shatteredpixeldungeon # Shattered Pixel Dungeon
          - com.todoist.Todoist # Todoist: To-Do List & Tasks
          - io.github.martchus.syncthingtray # Syncthing Tray
          - io.github.picocrypt.Picocrypt # Picocrypt
          - com.calibre_ebook.calibre # calibre
          - net.openra.OpenRA # openRA

    - name: Clone dotfiles
      when: ansible_distribution == 'Fedora'
      ansible.builtin.git:
        bare: true
        dest: $HOME/.dotfiles
        repo: https://github.com/MrQvest/.dotfiles

    - name: Checkout dotfiles
      when: ansible_distribution == 'Fedora'
      ansible.builtin.command: 'git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" checkout -f'

    - name: Configure dotfiles
      when: ansible_distribution == 'Fedora'
      ansible.builtin.command: 'git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" config --local status.showUntrackedFiles no'

    - name: Restart Pipewire
      when: ansible_distribution == 'Fedora'
      ansible.builtin.systemd_service:
        name: pipewire
        scope: user
        state: restarted
        daemon_reload: true

    - name: Restart Wireplumber
      when: ansible_distribution == 'Fedora'
      ansible.builtin.systemd_service:
        name: wireplumber
        scope: user
        state: restarted
        daemon_reload: true
