    - name: Enable RPM Fusion repositories
      when: ansible_distribution == 'Fedora'
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.dnf:
        disable_gpg_check: true
        state: present
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
