- name: push mpv config
  copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.config/mpv/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
  loop:
    - scripts
    - mpv.conf

- name: push mpv config to flatpak
  copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.var/app/io.mpv.Mpv/config/mpv/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
  loop:
    - scripts
    - mpv.conf
