- name: push topgrade config
  copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.config/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
  loop:
    - topgrade.toml
